<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
    
	<div class="row">
		<div class="span6">

			<?php View::process("Oferta", "Listado de Ofertas", "Listado de Ofertas"); ?>
			
		    <div class="dw-overflow">
		
		        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
		            <thead>
		                <tr>
		                    <th class="col-collapse" data-search="nombre">OFERTA</th>
		                    <th class="col-collapse" data-search="nombre">DETALLE</th>
		                    <th class="col-collapse" data-search="nombre">INGRESO</th>
		                    <th class="col-collapse" data-search="nombre">HORAS</th>
		                    <th class="col-collapse" data-search="nombre">SOCIO</th>
		                </tr>
		            </thead>
		            <tbody>
		                <?php foreach ($listItemsOfertas->items as $item) : ?>
		                    <?php $key_show = DwSecurity::getKey($item->id, 'show_perfil'); ?>
		                    <?php $key_upd = DwSecurity::getKey($item->id, 'upd_perfil'); ?>
		                    <?php $key_inac = DwSecurity::getKey($item->id, 'inactivar_perfil'); ?>
		                    <?php $key_reac = DwSecurity::getKey($item->id, 'reactivar_perfil'); ?>
		                    <tr>
		                        <td><?php echo $item->nombre ?></td>
		                        <td><?php echo $item->detalle ?></td>
		                        <td><?php echo $item->ingreso_at ?></td>
		                        <td><?php echo $item->horas ?></td>
		                        <td><?php echo $item->getUsuario()->email ?></td>
		                    </tr>
		                <?php endforeach; ?>
		            </tbody>
		        </table>
		
		    </div>		

       		<div>
        		<?php echo DwHtml::button("bdt/oferta/listar/", 'ver todas', array('class'=>'btn-info'), 'list', APP_AJAX); ?>   |   <?php echo DwHtml::button("bdt/oferta/create/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        	</div>		
		</div>    
		<div class="span6">

			<?php View::process("Solicitud", "Listado de Solicitudes", "Listado de Solicitudes"); ?>		
		
		    <div class="dw-overflow">
		
		        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
		            <thead>
		                <tr>
		                    <th class="col-collapse" data-search="nombre">SOLICITUD</th>
		                    <th class="col-collapse" data-search="nombre">DETALLE</th>
		                    <th class="col-collapse" data-search="nombre">INGRESO</th>
		                    <th class="col-collapse" data-search="nombre">HORAS</th>
		                    <th class="col-collapse" data-search="nombre">SOCIO</th>
		                </tr>
		            </thead>
		            <tbody>
		                <?php foreach ($listItemsSolicitudes->items as $item) : ?>
		                    <?php $key_show = DwSecurity::getKey($item->id, 'show_perfil'); ?>
		                    <?php $key_upd = DwSecurity::getKey($item->id, 'upd_perfil'); ?>
		                    <?php $key_inac = DwSecurity::getKey($item->id, 'inactivar_perfil'); ?>
		                    <?php $key_reac = DwSecurity::getKey($item->id, 'reactivar_perfil'); ?>
		                    <tr>
		                        <td><?php echo $item->nombre ?></td>
		                        <td><?php echo $item->detalle ?></td>
		                        <td><?php echo $item->ingreso_at ?></td>
		                        <td><?php echo $item->horas ?></td>
		                        <td><?php echo $item->getUsuario()->email ?></td>
		                    </tr>
		                <?php endforeach; ?>
		            </tbody>
		        </table>
		
		    </div>		

       		<div>
        		<?php echo DwHtml::button("bdt/solicitud/listar/", 'ver todas', array('class'=>'btn-info'), 'list', APP_AJAX); ?>   |   <?php echo DwHtml::button("bdt/solicitud/create/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        	</div>
        			
		</div>    
	
	</div>
	

    
    
</div>