<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id' => 'form', 'class' => 'dw-validate')); ?>

    <div class="row-fluid">
        <div class="span4">
            <?php echo DwForm::dbSelect('demanda.oferta_id', 'nombre', array('bdt/oferta', 'getItems'), NULL, array('class' => 'input-xxlarge input-required mask-pint show-errors'), Session::get('id_oferta'), 'Oferta'); ?>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span4">
            <?php echo DwForm::text('demanda.horas', array('class' => 'mask-alphanum show-error'), NULL, 'Cantidad de horas'); ?>
        </div>
    </div>    

    <div class="row-fluid">
        <div class="span4">
            <?php echo DwForm::textarea('demanda.detalle', array('class' => 'mask-alphanum show-error'), NULL, 'Detalle'); ?>
        </div>
    </div>
        
    
    <div class="row-fluid">
        <div class="form-actions">
            <?php echo DwButton::save('Guardar Demanda'); ?>
            <?php echo DwButton::reset('form'); ?>
            <?php echo DwButton::cancel('bdt/demanda/listar/'); ?>
        </div>
    </div>
    <?php echo DwForm::hiddenKey('demanda.id', $demanda->id); ?>
    <?php echo DwForm::hiddenKey('demanda.usuario_id', Session::get('id_us')); ?>
    <?php echo DwForm::close(); ?>

</div>