<?php View::notify(); ?>

<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"bdt/oferta/categorias/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

	<div class="row row-bdt">
		<div class="span1">
			<div><a href="http://localhost/bdt/bdt/oferta/categorias/1"><img src="/bdt/default/img/bdt/ico-categoria-educacion.png"></a></div>
           	<div>EDUCACION</div>		
		</div>
		<div class="span1">
			<div><a href="http://localhost/bdt/bdt/oferta/categorias/2"><img src="/bdt/default/img/bdt/ico-categoria-hogar.png"></a></div>
           	<div>HOGAR</div>		
		</div>
		<div class="span1">
			<div><a href="http://localhost/bdt/bdt/oferta/categorias/3"><img src="/bdt/default/img/bdt/ico-categoria-arte.png"></a></div>
            <div>ARTE</div>
		</div>
		<div class="span1">
			<div><a href="http://localhost/bdt/bdt/oferta/categorias/4"><img src="/bdt/default/img/bdt/ico-categoria-estetica.png"></a></div>
            <div>ESTETICA</div>
		</div>
		<div class="span1">
			<div><a href="http://localhost/bdt/bdt/oferta/categorias/5"><img src="/bdt/default/img/bdt/ico-categoria-medicina.png"></a></div>
            <div>MEDICINA</div>
		</div>
		<div class="span1">
			<div><a href="http://localhost/bdt/bdt/oferta/categorias/6"><img src="/bdt/default/img/bdt/ico-categoria-asociacion.png"></a></div>
            <div>ASOCIACION</div>
		</div>
		<div class="span1">
			<div><a href="http://localhost/bdt/bdt/oferta/categorias/7"><img src="/bdt/default/img/bdt/ico-categoria-oficios.png"></a></div>
           	<div>OFICIOS</div>		
		</div>
		<div class="span1">
			<div><a href="http://localhost/bdt/bdt/oferta/categorias/8"><img src="/bdt/default/img/bdt/ico-categoria-otras.png"></a></div>
           	<div>OTRAS</div>		
		</div>
	</div>  
	<br>
	<?php View::process($page_module, $page_title, $set_title); ?>
    <div class="dw-overflow">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th class="col-collapse" data-search="nombre">OFERTA</th>
                    <th class="col-collapse" data-search="nombre">DETALLE</th>
                    <th class="col-collapse" data-search="nombre">INGRESO</th>
                    <th class="col-collapse" data-search="nombre">HORAS DISPONIBLES</th>
                    <th class="col-collapse" data-search="nombre">SOCIO</th>
                    <th class="btn-actions no-responsive">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($listItems->items as $item) : ?>
                    <?php $key_show = DwSecurity::getKey($item->id, 'show_perfil'); ?>
                    <?php $key_upd = DwSecurity::getKey($item->id, 'upd_perfil'); ?>
                    <?php $key_inac = DwSecurity::getKey($item->id, 'inactivar_perfil'); ?>
                    <?php $key_reac = DwSecurity::getKey($item->id, 'reactivar_perfil'); ?>
                    <tr>
                        <td><?php echo $item->nombre ?></td>
                        <td><?php echo $item->detalle ?></td>
                        <td><?php echo $item->ingreso_at ?></td>
                        <td><?php echo $item->horas ?></td>
                        <td><?php echo $item->getUsuario()->email ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Aceptar Oferta', "bdt/oferta/ok/$key_show/",array('class'=>'js-confirm', 'confirm-title'=>'Aceptar Oferta', 'confirm-body'=>'Está seguro de aceptar la oferta? <br />Recuerda que esta operación no se puede reversar.'), 'success', 'thumbs-up'); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$listItems, 'url'=>"bdt/oferta/listar/$order/")); ?>

</div>