<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id' => 'form', 'class' => 'dw-validate')); ?>

    <div class="row-fluid">
        <div class="span4">
            <?php echo DwForm::text('categoriadetrabajo.nombre', array('class' => 'mask-alphanum show-error'), NULL, 'Categoría'); ?>
        </div>
    </div>
    
    <div class="row-fluid">
        <div class="span4">
            <?php echo DwForm::text('categoriadetrabajo.fotografia', array('class' => 'mask-alphanum show-error'), NULL, 'Imagen'); ?>
        </div>
    </div>       

    <div class="row-fluid">
        <div class="span4">
            <?php echo DwForm::textarea('categoriadetrabajo.detalle', array('class' => 'mask-alphanum show-error'), NULL, 'Detalle'); ?>
        </div>
    </div>    

    <div class="row-fluid">
        <div class="form-actions">
            <?php echo DwButton::save('Guardar categoría'); ?>
            <?php echo DwButton::reset('form'); ?>
            <?php echo DwButton::cancel('bdt/categoriadetrabajo/listar/'); ?>
        </div>
    </div>
    <?php echo DwForm::hiddenKey('categoriadetrabajo.id', $categoriadetrabajo->id); ?>
    <?php echo DwForm::close(); ?>

</div>