<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">
    
	<div class="row-fluid">
		<div class="span6" style="text-align: center;">
        <img src="img/bdt/logo.png" alt="...">
        <br>
        <br>
        <br>
        <h4>Ingresar</h4>
        <?php echo DwHtml::button("sistema/login/entrar/", '', array('class'=>'btn-success'), 'signin', FALSE); ?>
            
		</div>    
        <div class="span6">
		<h4 class="titulo">¿Qué es el Banco de Tiempo?</h4>
        <p>
        Un Banco de Tiempo es un grupo de personas motivadas para intercambiar tiempo, 
        dedicándolo a tareas puntuales ya sea para colaborar con instituciones o grupos de la comunidad, 
        como también entre los mismos asociados. La unidad de intercambio y de valor es la hora, 
        independientemente del servicio que se ofrezca o que se reciba. 
        </p>
        <p>
        Si estás interesado en aprovechar alguna de las ofertas, 
        solamente tenés que ponerte en contacto con la Asociación, indicar tu necesidad 
        y nosotros te derivaremos con uno de los socios disponibles, 
        además de proveerte mayores detalles sobre su perfil.
        </p>		
		</div>    
	</div>
    <br>
    <br>
    <div class="row-fluid">
        <div class="span4">
            <h4 class="titulo">Sacar del medio el dinero</h4>
            <div class="row-fluid">
				<div class="span4" style="text-align: center;">
		        <i class="icon-refresh icon-refresh icon-5x"></i>
				</div>
				<div class="span8">
		        Intercambiamos tiempo como una forma de demostrar que creemos en formas más genuina de relacionarnos.
				</div>
             </div>
        </div>
    	<div class="span4">
            <h4 class="titulo">Igualdad en la valoración del aporte</h4>
            <div class="row-fluid">
				<div class="span4" style="text-align: center;">
		        <i class="icon-resize-small icon-resize-small icon-5x"></i>
				</div>
				<div class="span8">
		        Creemos que lo que debe valorarse es la participación y el intercambio mutuo sin distinción de tipos de trabajo.
				</div>
             </div>
        </div>
        <div class="span4">
            <h4 class="titulo">Compromiso social</h4>
            <div class="row-fluid">
				<div class="span4" style="text-align: center;">
		        <i class="icon-globe icon-globe icon-5x"></i>
				</div>
				<div class="span8">
		        Uno de los objetivos centrales es poder brindar nuestro trabajo para colaborar con las necesidades de instituciones, organizaciones y vecinos del barrio.
				</div>
             </div>
        </div>
    </div>
    
    <div class="row-fluid">
        <div class="span4">
            <h4 class="titulo">Compartir la experiencia</h4>
            <div class="row-fluid">
				<div class="span4" style="text-align: center;">
		        <i class="icon-cloud-upload icon-cloud-upload icon-5x"></i>
				</div>
				<div class="span8">
		        Ponemos a disposición de organizaciones e instituciones el formato del Banco de Tiempo, para que esta experiencia pueda replicarse.
				</div>
             </div> 
        </div>
        <div class="span4">
            <h4 class="titulo">Categorías de trabajos</h4>
            <div class="row-fluid">
				<div class="span4" style="text-align: center;">
		        <i class="icon-list icon-list icon-5x"></i>
				</div>
				<div class="span8">
		        Educación, Oficios, Arte, Estética, Medicina, Acompañamiento, Cocina, Servicios, Asesoramiento, Asociación, Transporte.
				</div>
             </div>
        </div>
        <div class="span4">
			<h4 class="titulo">Contacto con el Banco de Tiempo</h4>
            <div class="row-fluid">
				<div class="span4" style="text-align: center;">
		        <i class="icon-envelope icon-envelope icon-5x"></i>
				</div>
				<div class="span8">
		        bdt@graduadostandil.org.ar
		        <br>
		        info@graduadostandil.org.ar
				</div>
      		</div>            
     	</div>
        
    </div>              
    
</div>