<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id' => 'form', 'class' => 'dw-validate')); ?>

    <div class="row-fluid">
        <div class="span4">
            <?php echo DwForm::text('solicitud.nombre', array('class' => 'mask-alphanum show-error'), NULL, 'Título'); ?>
        </div>
    </div> 

    <div class="row-fluid">
        <div class="span4">
            <?php echo DwForm::dbSelect('solicitud.categoriadetrabajo_id', 'nombre', array('bdt/categoriadetrabajo', 'getItems'), NULL, array('class' => 'input-xxlarge input-required mask-pint show-errors'), NULL, 'Categoría de Trabajo'); ?>
        </div>
    </div>
    
    <div class="row-fluid">
        <div class="span4">
            <?php echo DwForm::text('solicitud.horas', array('class' => 'mask-alphanum show-error'), NULL, 'Cantidad de horas'); ?>
        </div>
    </div>    

    <div class="row-fluid">
        <div class="span4">
            <?php echo DwForm::textarea('solicitud.detalle', array('class' => 'mask-alphanum show-error'), NULL, 'Detalle'); ?>
        </div>
    </div>
    
    
    <div class="row-fluid">
        <div class="form-actions">
            <?php echo DwButton::save('Guardar Solicitud'); ?>
            <?php echo DwButton::reset('form'); ?>
            <?php echo DwButton::cancel('bdt/solicitud/listar/'); ?>
        </div>
    </div>
    <?php echo DwForm::hiddenKey('solicitud.id', $solicitud->id); ?>
    <?php echo DwForm::hiddenKey('solicitud.usuario_id', Session::get('id_us')); ?>
    <?php echo DwForm::close(); ?>

</div>